server:
  port: 7003

eureka:
  instance:
    hostname: eureka7003.com
  client:
    register-with-eureka: true # Register center doesn't need to register itself
    fetch-registry: true # Register center doesn't need to fetch service
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka, http://eureka7002.com:7002/eureka # discover other servers in the cluster

spring:
  application:
    name: springcloud-eureka-server