server:
  port: 8001

eureka:
  instance:
    hostname: springcloud-service.com
    # instance-id: springcloud-service-1 # alias for singleton service, must close it for repeating registration
    prefer-ip-address: true # change to physical ip-addr of current service
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/, http://eureka7002.com:7002/eureka/, http://eureka7003.com:7003/eureka/ # Register a service into a cluster
    fetch-registry: true
    register-with-eureka: true

spring:
  application:
    name: springcloud-service-8001-hystrix

info:
  app.name: springcloud-service-hystrix
  company.name: seanforfun.github.io
  build.artifactId: @project.artifactId@
  build.version: @project.version@
  port: ${server.port}
