server:
  port: 7001

eureka:
  instance:
    hostname: eureka7001.com
  client:
    register-with-eureka: false # Register center doesn't need to register itself
    fetch-registry: false # Register center doesn't need to fetch service
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/, http://eureka7003.com:7003/eureka/ # discover other servers in the cluster